// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgChat.proto

package utouu.im.protobuf.pb;

public final class MsgChat {
  private MsgChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqSdkPrimaryChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ReqSdkPrimaryChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    boolean hasToAccount();
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    java.lang.String getToAccount();
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getToAccountBytes();

    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    int getType();

    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    boolean hasMediaBytes();
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    com.google.protobuf.ByteString getMediaBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.ReqSdkPrimaryChat}
   *
   * <pre>
   *REQ_SDK_PRIMARY_CHAT = 200001;//sdk请求文字私聊别人
   * </pre>
   */
  public static final class ReqSdkPrimaryChat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ReqSdkPrimaryChat)
      ReqSdkPrimaryChatOrBuilder {
    // Use ReqSdkPrimaryChat.newBuilder() to construct.
    private ReqSdkPrimaryChat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqSdkPrimaryChat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqSdkPrimaryChat defaultInstance;
    public static ReqSdkPrimaryChat getDefaultInstance() {
      return defaultInstance;
    }

    public ReqSdkPrimaryChat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqSdkPrimaryChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              toAccount_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              text_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mediaBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.class, utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqSdkPrimaryChat> PARSER =
        new com.google.protobuf.AbstractParser<ReqSdkPrimaryChat>() {
      public ReqSdkPrimaryChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqSdkPrimaryChat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqSdkPrimaryChat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object toAccount_;
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public boolean hasToAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public java.lang.String getToAccount() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToAccountBytes() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEDIABYTES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mediaBytes_;
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public boolean hasMediaBytes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public com.google.protobuf.ByteString getMediaBytes() {
      return mediaBytes_;
    }

    private void initFields() {
      toAccount_ = "";
      type_ = 0;
      text_ = "";
      mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, mediaBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mediaBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ReqSdkPrimaryChat}
     *
     * <pre>
     *REQ_SDK_PRIMARY_CHAT = 200001;//sdk请求文字私聊别人
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ReqSdkPrimaryChat)
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.class, utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat build() {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat buildPartial() {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat result = new utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.toAccount_ = toAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mediaBytes_ = mediaBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat other) {
        if (other == utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat.getDefaultInstance()) return this;
        if (other.hasToAccount()) {
          bitField0_ |= 0x00000001;
          toAccount_ = other.toAccount_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasMediaBytes()) {
          setMediaBytes(other.getMediaBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToAccount()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryChat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object toAccount_ = "";
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public boolean hasToAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public java.lang.String getToAccount() {
        java.lang.Object ref = toAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToAccountBytes() {
        java.lang.Object ref = toAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder setToAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        toAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder clearToAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        toAccount_ = getDefaultInstance().getToAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder setToAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        toAccount_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public boolean hasMediaBytes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public com.google.protobuf.ByteString getMediaBytes() {
        return mediaBytes_;
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder setMediaBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mediaBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder clearMediaBytes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mediaBytes_ = getDefaultInstance().getMediaBytes();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ReqSdkPrimaryChat)
    }

    static {
      defaultInstance = new ReqSdkPrimaryChat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ReqSdkPrimaryChat)
  }

  public interface ResSdkPrimaryChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ResSdkPrimaryChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code ProtoNet.ResSdkPrimaryChat}
   *
   * <pre>
   *RES_SDK_PRIMARY_CHAT  = 200002;//sdk返回文字私聊别人
   * </pre>
   */
  public static final class ResSdkPrimaryChat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ResSdkPrimaryChat)
      ResSdkPrimaryChatOrBuilder {
    // Use ResSdkPrimaryChat.newBuilder() to construct.
    private ResSdkPrimaryChat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResSdkPrimaryChat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResSdkPrimaryChat defaultInstance;
    public static ResSdkPrimaryChat getDefaultInstance() {
      return defaultInstance;
    }

    public ResSdkPrimaryChat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResSdkPrimaryChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.class, utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.Builder.class);
    }

    public static com.google.protobuf.Parser<ResSdkPrimaryChat> PARSER =
        new com.google.protobuf.AbstractParser<ResSdkPrimaryChat>() {
      public ResSdkPrimaryChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResSdkPrimaryChat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResSdkPrimaryChat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ResSdkPrimaryChat}
     *
     * <pre>
     *RES_SDK_PRIMARY_CHAT  = 200002;//sdk返回文字私聊别人
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ResSdkPrimaryChat)
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.class, utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryChat_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat build() {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat buildPartial() {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat result = new utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat other) {
        if (other == utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryChat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ResSdkPrimaryChat)
    }

    static {
      defaultInstance = new ResSdkPrimaryChat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ResSdkPrimaryChat)
  }

  public interface NotifySomeOnePrimaryChatToMeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.NotifySomeOnePrimaryChatToMe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    boolean hasFromAccount();
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    java.lang.String getFromAccount();
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromAccountBytes();

    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    int getType();

    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    boolean hasMediaBytes();
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    com.google.protobuf.ByteString getMediaBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.NotifySomeOnePrimaryChatToMe}
   *
   * <pre>
   *NOTIFY_SOMEONE_PRIMARY_CHAT_TO_ME = 200003;//通知某人私聊我
   * </pre>
   */
  public static final class NotifySomeOnePrimaryChatToMe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.NotifySomeOnePrimaryChatToMe)
      NotifySomeOnePrimaryChatToMeOrBuilder {
    // Use NotifySomeOnePrimaryChatToMe.newBuilder() to construct.
    private NotifySomeOnePrimaryChatToMe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotifySomeOnePrimaryChatToMe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotifySomeOnePrimaryChatToMe defaultInstance;
    public static NotifySomeOnePrimaryChatToMe getDefaultInstance() {
      return defaultInstance;
    }

    public NotifySomeOnePrimaryChatToMe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotifySomeOnePrimaryChatToMe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fromAccount_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              text_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mediaBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.class, utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.Builder.class);
    }

    public static com.google.protobuf.Parser<NotifySomeOnePrimaryChatToMe> PARSER =
        new com.google.protobuf.AbstractParser<NotifySomeOnePrimaryChatToMe>() {
      public NotifySomeOnePrimaryChatToMe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifySomeOnePrimaryChatToMe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotifySomeOnePrimaryChatToMe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROMACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object fromAccount_;
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public boolean hasFromAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public java.lang.String getFromAccount() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromAccountBytes() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEDIABYTES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mediaBytes_;
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public boolean hasMediaBytes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes mediaBytes = 4;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public com.google.protobuf.ByteString getMediaBytes() {
      return mediaBytes_;
    }

    private void initFields() {
      fromAccount_ = "";
      type_ = 0;
      text_ = "";
      mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, mediaBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mediaBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.NotifySomeOnePrimaryChatToMe}
     *
     * <pre>
     *NOTIFY_SOMEONE_PRIMARY_CHAT_TO_ME = 200003;//通知某人私聊我
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.NotifySomeOnePrimaryChatToMe)
        utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.class, utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe build() {
        utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe buildPartial() {
        utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe result = new utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromAccount_ = fromAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mediaBytes_ = mediaBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe other) {
        if (other == utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe.getDefaultInstance()) return this;
        if (other.hasFromAccount()) {
          bitField0_ |= 0x00000001;
          fromAccount_ = other.fromAccount_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasMediaBytes()) {
          setMediaBytes(other.getMediaBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromAccount()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.NotifySomeOnePrimaryChatToMe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fromAccount_ = "";
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public boolean hasFromAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public java.lang.String getFromAccount() {
        java.lang.Object ref = fromAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromAccountBytes() {
        java.lang.Object ref = fromAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder clearFromAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromAccount_ = getDefaultInstance().getFromAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromAccount_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public boolean hasMediaBytes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public com.google.protobuf.ByteString getMediaBytes() {
        return mediaBytes_;
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder setMediaBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mediaBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mediaBytes = 4;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder clearMediaBytes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mediaBytes_ = getDefaultInstance().getMediaBytes();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.NotifySomeOnePrimaryChatToMe)
    }

    static {
      defaultInstance = new NotifySomeOnePrimaryChatToMe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.NotifySomeOnePrimaryChatToMe)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ReqSdkPrimaryChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ResSdkPrimaryChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ResSdkPrimaryChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgChat.proto\022\010ProtoNet\"V\n\021ReqSdkPrima" +
      "ryChat\022\021\n\ttoAccount\030\001 \002(\t\022\014\n\004type\030\002 \002(\005\022" +
      "\014\n\004text\030\003 \001(\t\022\022\n\nmediaBytes\030\004 \001(\014\"#\n\021Res" +
      "SdkPrimaryChat\022\016\n\006result\030\001 \002(\005\"c\n\034Notify" +
      "SomeOnePrimaryChatToMe\022\023\n\013fromAccount\030\001 " +
      "\002(\t\022\014\n\004type\030\002 \002(\005\022\014\n\004text\030\003 \001(\t\022\022\n\nmedia" +
      "Bytes\030\004 \001(\014B\026\n\024utouu.im.protobuf.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoNet_ReqSdkPrimaryChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ReqSdkPrimaryChat_descriptor,
        new java.lang.String[] { "ToAccount", "Type", "Text", "MediaBytes", });
    internal_static_ProtoNet_ResSdkPrimaryChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoNet_ResSdkPrimaryChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ResSdkPrimaryChat_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_NotifySomeOnePrimaryChatToMe_descriptor,
        new java.lang.String[] { "FromAccount", "Type", "Text", "MediaBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
