// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgChat.proto

package utouu.im.protobuf.pb;

public final class MsgChat {
  private MsgChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqSdkPrimaryTextChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ReqSdkPrimaryTextChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    boolean hasToAccount();
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    java.lang.String getToAccount();
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getToAccountBytes();

    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    boolean hasChatText();
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    java.lang.String getChatText();
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getChatTextBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.ReqSdkPrimaryTextChat}
   *
   * <pre>
   *REQ_SDK_PRIMARYTEXTCHAT = 200001;//sdk请求文字私聊别人
   * </pre>
   */
  public static final class ReqSdkPrimaryTextChat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ReqSdkPrimaryTextChat)
      ReqSdkPrimaryTextChatOrBuilder {
    // Use ReqSdkPrimaryTextChat.newBuilder() to construct.
    private ReqSdkPrimaryTextChat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqSdkPrimaryTextChat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqSdkPrimaryTextChat defaultInstance;
    public static ReqSdkPrimaryTextChat getDefaultInstance() {
      return defaultInstance;
    }

    public ReqSdkPrimaryTextChat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqSdkPrimaryTextChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              toAccount_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              chatText_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryTextChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.class, utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqSdkPrimaryTextChat> PARSER =
        new com.google.protobuf.AbstractParser<ReqSdkPrimaryTextChat>() {
      public ReqSdkPrimaryTextChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqSdkPrimaryTextChat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqSdkPrimaryTextChat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object toAccount_;
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public boolean hasToAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public java.lang.String getToAccount() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toAccount = 1;</code>
     *
     * <pre>
     *接受者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToAccountBytes() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATTEXT_FIELD_NUMBER = 2;
    private java.lang.Object chatText_;
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public boolean hasChatText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public java.lang.String getChatText() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chatText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChatTextBytes() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      toAccount_ = "";
      chatText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChatTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChatTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ReqSdkPrimaryTextChat}
     *
     * <pre>
     *REQ_SDK_PRIMARYTEXTCHAT = 200001;//sdk请求文字私聊别人
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ReqSdkPrimaryTextChat)
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryTextChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.class, utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        chatText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat build() {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat buildPartial() {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat result = new utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.toAccount_ = toAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chatText_ = chatText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat other) {
        if (other == utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat.getDefaultInstance()) return this;
        if (other.hasToAccount()) {
          bitField0_ |= 0x00000001;
          toAccount_ = other.toAccount_;
          onChanged();
        }
        if (other.hasChatText()) {
          bitField0_ |= 0x00000002;
          chatText_ = other.chatText_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToAccount()) {
          
          return false;
        }
        if (!hasChatText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.ReqSdkPrimaryTextChat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object toAccount_ = "";
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public boolean hasToAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public java.lang.String getToAccount() {
        java.lang.Object ref = toAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToAccountBytes() {
        java.lang.Object ref = toAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder setToAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        toAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder clearToAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        toAccount_ = getDefaultInstance().getToAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 1;</code>
       *
       * <pre>
       *接受者账号
       * </pre>
       */
      public Builder setToAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        toAccount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chatText_ = "";
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public boolean hasChatText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public java.lang.String getChatText() {
        java.lang.Object ref = chatText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            chatText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChatTextBytes() {
        java.lang.Object ref = chatText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chatText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder clearChatText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chatText_ = getDefaultInstance().getChatText();
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chatText_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ReqSdkPrimaryTextChat)
    }

    static {
      defaultInstance = new ReqSdkPrimaryTextChat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ReqSdkPrimaryTextChat)
  }

  public interface ResSdkPrimaryTextChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ResSdkPrimaryTextChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 primaryTextChatResult = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    boolean hasPrimaryTextChatResult();
    /**
     * <code>required int32 primaryTextChatResult = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    int getPrimaryTextChatResult();
  }
  /**
   * Protobuf type {@code ProtoNet.ResSdkPrimaryTextChat}
   *
   * <pre>
   *RES_SDK_PRIMARYTEXTCHAT  = 200002;
   * </pre>
   */
  public static final class ResSdkPrimaryTextChat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ResSdkPrimaryTextChat)
      ResSdkPrimaryTextChatOrBuilder {
    // Use ResSdkPrimaryTextChat.newBuilder() to construct.
    private ResSdkPrimaryTextChat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResSdkPrimaryTextChat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResSdkPrimaryTextChat defaultInstance;
    public static ResSdkPrimaryTextChat getDefaultInstance() {
      return defaultInstance;
    }

    public ResSdkPrimaryTextChat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResSdkPrimaryTextChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              primaryTextChatResult_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryTextChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.class, utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.Builder.class);
    }

    public static com.google.protobuf.Parser<ResSdkPrimaryTextChat> PARSER =
        new com.google.protobuf.AbstractParser<ResSdkPrimaryTextChat>() {
      public ResSdkPrimaryTextChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResSdkPrimaryTextChat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResSdkPrimaryTextChat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PRIMARYTEXTCHATRESULT_FIELD_NUMBER = 1;
    private int primaryTextChatResult_;
    /**
     * <code>required int32 primaryTextChatResult = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    public boolean hasPrimaryTextChatResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 primaryTextChatResult = 1;</code>
     *
     * <pre>
     *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
     * </pre>
     */
    public int getPrimaryTextChatResult() {
      return primaryTextChatResult_;
    }

    private void initFields() {
      primaryTextChatResult_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPrimaryTextChatResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, primaryTextChatResult_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, primaryTextChatResult_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ResSdkPrimaryTextChat}
     *
     * <pre>
     *RES_SDK_PRIMARYTEXTCHAT  = 200002;
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ResSdkPrimaryTextChat)
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryTextChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.class, utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        primaryTextChatResult_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat build() {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat buildPartial() {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat result = new utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.primaryTextChatResult_ = primaryTextChatResult_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat other) {
        if (other == utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat.getDefaultInstance()) return this;
        if (other.hasPrimaryTextChatResult()) {
          setPrimaryTextChatResult(other.getPrimaryTextChatResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrimaryTextChatResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.ResSdkPrimaryTextChat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int primaryTextChatResult_ ;
      /**
       * <code>required int32 primaryTextChatResult = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public boolean hasPrimaryTextChatResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 primaryTextChatResult = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public int getPrimaryTextChatResult() {
        return primaryTextChatResult_;
      }
      /**
       * <code>required int32 primaryTextChatResult = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public Builder setPrimaryTextChatResult(int value) {
        bitField0_ |= 0x00000001;
        primaryTextChatResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 primaryTextChatResult = 1;</code>
       *
       * <pre>
       *0代表聊天发送成功,1代表聊天发送失败,其他枚举后续定义
       * </pre>
       */
      public Builder clearPrimaryTextChatResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        primaryTextChatResult_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ResSdkPrimaryTextChat)
    }

    static {
      defaultInstance = new ResSdkPrimaryTextChat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ResSdkPrimaryTextChat)
  }

  public interface ResSdkSomeOnePrimaryTextChatToMeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ResSdkSomeOnePrimaryTextChatToMe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    boolean hasFromAccount();
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    java.lang.String getFromAccount();
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromAccountBytes();

    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    boolean hasChatText();
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    java.lang.String getChatText();
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getChatTextBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.ResSdkSomeOnePrimaryTextChatToMe}
   *
   * <pre>
   *RES_SDK_SOMEONEPRIMARYTEXTCHATTOME  = 200003;//返回sdk某人给我私聊了文本消息
   * </pre>
   */
  public static final class ResSdkSomeOnePrimaryTextChatToMe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ResSdkSomeOnePrimaryTextChatToMe)
      ResSdkSomeOnePrimaryTextChatToMeOrBuilder {
    // Use ResSdkSomeOnePrimaryTextChatToMe.newBuilder() to construct.
    private ResSdkSomeOnePrimaryTextChatToMe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResSdkSomeOnePrimaryTextChatToMe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResSdkSomeOnePrimaryTextChatToMe defaultInstance;
    public static ResSdkSomeOnePrimaryTextChatToMe getDefaultInstance() {
      return defaultInstance;
    }

    public ResSdkSomeOnePrimaryTextChatToMe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResSdkSomeOnePrimaryTextChatToMe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fromAccount_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              chatText_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.class, utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.Builder.class);
    }

    public static com.google.protobuf.Parser<ResSdkSomeOnePrimaryTextChatToMe> PARSER =
        new com.google.protobuf.AbstractParser<ResSdkSomeOnePrimaryTextChatToMe>() {
      public ResSdkSomeOnePrimaryTextChatToMe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResSdkSomeOnePrimaryTextChatToMe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResSdkSomeOnePrimaryTextChatToMe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROMACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object fromAccount_;
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public boolean hasFromAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public java.lang.String getFromAccount() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromAccount = 1;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromAccountBytes() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATTEXT_FIELD_NUMBER = 2;
    private java.lang.Object chatText_;
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public boolean hasChatText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public java.lang.String getChatText() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chatText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chatText = 2;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChatTextBytes() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fromAccount_ = "";
      chatText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChatTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChatTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ResSdkSomeOnePrimaryTextChatToMe}
     *
     * <pre>
     *RES_SDK_SOMEONEPRIMARYTEXTCHATTOME  = 200003;//返回sdk某人给我私聊了文本消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ResSdkSomeOnePrimaryTextChatToMe)
        utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.class, utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        chatText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgChat.internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe build() {
        utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe buildPartial() {
        utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe result = new utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromAccount_ = fromAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chatText_ = chatText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe) {
          return mergeFrom((utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe other) {
        if (other == utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe.getDefaultInstance()) return this;
        if (other.hasFromAccount()) {
          bitField0_ |= 0x00000001;
          fromAccount_ = other.fromAccount_;
          onChanged();
        }
        if (other.hasChatText()) {
          bitField0_ |= 0x00000002;
          chatText_ = other.chatText_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromAccount()) {
          
          return false;
        }
        if (!hasChatText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgChat.ResSdkSomeOnePrimaryTextChatToMe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fromAccount_ = "";
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public boolean hasFromAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public java.lang.String getFromAccount() {
        java.lang.Object ref = fromAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromAccountBytes() {
        java.lang.Object ref = fromAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder clearFromAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromAccount_ = getDefaultInstance().getFromAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 1;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromAccount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chatText_ = "";
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public boolean hasChatText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public java.lang.String getChatText() {
        java.lang.Object ref = chatText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            chatText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChatTextBytes() {
        java.lang.Object ref = chatText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chatText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder clearChatText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chatText_ = getDefaultInstance().getChatText();
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 2;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chatText_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ResSdkSomeOnePrimaryTextChatToMe)
    }

    static {
      defaultInstance = new ResSdkSomeOnePrimaryTextChatToMe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ResSdkSomeOnePrimaryTextChatToMe)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ReqSdkPrimaryTextChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ResSdkPrimaryTextChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgChat.proto\022\010ProtoNet\"<\n\025ReqSdkPrima" +
      "ryTextChat\022\021\n\ttoAccount\030\001 \002(\t\022\020\n\010chatTex" +
      "t\030\002 \002(\t\"6\n\025ResSdkPrimaryTextChat\022\035\n\025prim" +
      "aryTextChatResult\030\001 \002(\005\"I\n ResSdkSomeOne" +
      "PrimaryTextChatToMe\022\023\n\013fromAccount\030\001 \002(\t" +
      "\022\020\n\010chatText\030\002 \002(\tB\026\n\024utouu.im.protobuf." +
      "pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoNet_ReqSdkPrimaryTextChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ReqSdkPrimaryTextChat_descriptor,
        new java.lang.String[] { "ToAccount", "ChatText", });
    internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoNet_ResSdkPrimaryTextChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ResSdkPrimaryTextChat_descriptor,
        new java.lang.String[] { "PrimaryTextChatResult", });
    internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ResSdkSomeOnePrimaryTextChatToMe_descriptor,
        new java.lang.String[] { "FromAccount", "ChatText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
