// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgNode.proto

package utouu.im.protobuf.pb;

public final class MsgNode {
  private MsgNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqNodeServerCreateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ReqNodeServerCreate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    boolean hasServerip();
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    java.lang.String getServerip();
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    com.google.protobuf.ByteString
        getServeripBytes();

    /**
     * <code>required int32 serverport = 2;</code>
     *
     * <pre>
     *节点port
     * </pre>
     */
    boolean hasServerport();
    /**
     * <code>required int32 serverport = 2;</code>
     *
     * <pre>
     *节点port
     * </pre>
     */
    int getServerport();
  }
  /**
   * Protobuf type {@code ProtoNet.ReqNodeServerCreate}
   *
   * <pre>
   *REQ_NODE_SERVER_CREATE = 800000;//请求节点服务器创建链接成功
   * </pre>
   */
  public static final class ReqNodeServerCreate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ReqNodeServerCreate)
      ReqNodeServerCreateOrBuilder {
    // Use ReqNodeServerCreate.newBuilder() to construct.
    private ReqNodeServerCreate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqNodeServerCreate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqNodeServerCreate defaultInstance;
    public static ReqNodeServerCreate getDefaultInstance() {
      return defaultInstance;
    }

    public ReqNodeServerCreate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqNodeServerCreate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serverip_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverport_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_ReqNodeServerCreate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_ReqNodeServerCreate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.class, utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqNodeServerCreate> PARSER =
        new com.google.protobuf.AbstractParser<ReqNodeServerCreate>() {
      public ReqNodeServerCreate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqNodeServerCreate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqNodeServerCreate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private java.lang.Object serverip_;
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    public boolean hasServerip() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    public java.lang.String getServerip() {
      java.lang.Object ref = serverip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *节点ip
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServeripBytes() {
      java.lang.Object ref = serverip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 2;
    private int serverport_;
    /**
     * <code>required int32 serverport = 2;</code>
     *
     * <pre>
     *节点port
     * </pre>
     */
    public boolean hasServerport() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverport = 2;</code>
     *
     * <pre>
     *节点port
     * </pre>
     */
    public int getServerport() {
      return serverport_;
    }

    private void initFields() {
      serverip_ = "";
      serverport_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerport()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverport_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverport_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ReqNodeServerCreate}
     *
     * <pre>
     *REQ_NODE_SERVER_CREATE = 800000;//请求节点服务器创建链接成功
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ReqNodeServerCreate)
        utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_ReqNodeServerCreate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_ReqNodeServerCreate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.class, utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverport_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_ReqNodeServerCreate_descriptor;
      }

      public utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate build() {
        utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate buildPartial() {
        utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate result = new utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverip_ = serverip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverport_ = serverport_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate) {
          return mergeFrom((utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate other) {
        if (other == utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate.getDefaultInstance()) return this;
        if (other.hasServerip()) {
          bitField0_ |= 0x00000001;
          serverip_ = other.serverip_;
          onChanged();
        }
        if (other.hasServerport()) {
          setServerport(other.getServerport());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerip()) {
          
          return false;
        }
        if (!hasServerport()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgNode.ReqNodeServerCreate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverip_ = "";
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public boolean hasServerip() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public java.lang.String getServerip() {
        java.lang.Object ref = serverip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServeripBytes() {
        java.lang.Object ref = serverip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public Builder setServerip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public Builder clearServerip() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverip_ = getDefaultInstance().getServerip();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *节点ip
       * </pre>
       */
      public Builder setServeripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }

      private int serverport_ ;
      /**
       * <code>required int32 serverport = 2;</code>
       *
       * <pre>
       *节点port
       * </pre>
       */
      public boolean hasServerport() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverport = 2;</code>
       *
       * <pre>
       *节点port
       * </pre>
       */
      public int getServerport() {
        return serverport_;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       *
       * <pre>
       *节点port
       * </pre>
       */
      public Builder setServerport(int value) {
        bitField0_ |= 0x00000002;
        serverport_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       *
       * <pre>
       *节点port
       * </pre>
       */
      public Builder clearServerport() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverport_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ReqNodeServerCreate)
    }

    static {
      defaultInstance = new ReqNodeServerCreate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ReqNodeServerCreate)
  }

  public interface NotifyNodeSomeOnePrimaryChatToMeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.NotifyNodeSomeOnePrimaryChatToMe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string serverip = 1;</code>
     */
    boolean hasServerip();
    /**
     * <code>required string serverip = 1;</code>
     */
    java.lang.String getServerip();
    /**
     * <code>required string serverip = 1;</code>
     */
    com.google.protobuf.ByteString
        getServeripBytes();

    /**
     * <code>required int32 serverport = 2;</code>
     */
    boolean hasServerport();
    /**
     * <code>required int32 serverport = 2;</code>
     */
    int getServerport();

    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    boolean hasFromAccount();
    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    java.lang.String getFromAccount();
    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromAccountBytes();

    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    boolean hasToAccount();
    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    java.lang.String getToAccount();
    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getToAccountBytes();

    /**
     * <code>required int32 type = 5;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 5;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    int getType();

    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional bytes mediaBytes = 7;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    boolean hasMediaBytes();
    /**
     * <code>optional bytes mediaBytes = 7;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    com.google.protobuf.ByteString getMediaBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.NotifyNodeSomeOnePrimaryChatToMe}
   *
   * <pre>
   *NOTIFY_NODE_SOMEONE_PRIMARYCHAT_TO_ME = 800001;//通知其他服务器节点某人私聊某人
   * </pre>
   */
  public static final class NotifyNodeSomeOnePrimaryChatToMe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.NotifyNodeSomeOnePrimaryChatToMe)
      NotifyNodeSomeOnePrimaryChatToMeOrBuilder {
    // Use NotifyNodeSomeOnePrimaryChatToMe.newBuilder() to construct.
    private NotifyNodeSomeOnePrimaryChatToMe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotifyNodeSomeOnePrimaryChatToMe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotifyNodeSomeOnePrimaryChatToMe defaultInstance;
    public static NotifyNodeSomeOnePrimaryChatToMe getDefaultInstance() {
      return defaultInstance;
    }

    public NotifyNodeSomeOnePrimaryChatToMe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyNodeSomeOnePrimaryChatToMe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serverip_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverport_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              fromAccount_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              toAccount_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              type_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              text_ = bs;
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              mediaBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.class, utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.Builder.class);
    }

    public static com.google.protobuf.Parser<NotifyNodeSomeOnePrimaryChatToMe> PARSER =
        new com.google.protobuf.AbstractParser<NotifyNodeSomeOnePrimaryChatToMe>() {
      public NotifyNodeSomeOnePrimaryChatToMe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyNodeSomeOnePrimaryChatToMe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyNodeSomeOnePrimaryChatToMe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private java.lang.Object serverip_;
    /**
     * <code>required string serverip = 1;</code>
     */
    public boolean hasServerip() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverip = 1;</code>
     */
    public java.lang.String getServerip() {
      java.lang.Object ref = serverip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServeripBytes() {
      java.lang.Object ref = serverip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 2;
    private int serverport_;
    /**
     * <code>required int32 serverport = 2;</code>
     */
    public boolean hasServerport() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverport = 2;</code>
     */
    public int getServerport() {
      return serverport_;
    }

    public static final int FROMACCOUNT_FIELD_NUMBER = 3;
    private java.lang.Object fromAccount_;
    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public boolean hasFromAccount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public java.lang.String getFromAccount() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromAccount = 3;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromAccountBytes() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOACCOUNT_FIELD_NUMBER = 4;
    private java.lang.Object toAccount_;
    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public boolean hasToAccount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public java.lang.String getToAccount() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toAccount = 4;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToAccountBytes() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>required int32 type = 5;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 type = 5;</code>
     *
     * <pre>
     *聊天类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int TEXT_FIELD_NUMBER = 6;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 6;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEDIABYTES_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString mediaBytes_;
    /**
     * <code>optional bytes mediaBytes = 7;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public boolean hasMediaBytes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes mediaBytes = 7;</code>
     *
     * <pre>
     *音频文件二进制流
     * </pre>
     */
    public com.google.protobuf.ByteString getMediaBytes() {
      return mediaBytes_;
    }

    private void initFields() {
      serverip_ = "";
      serverport_ = 0;
      fromAccount_ = "";
      toAccount_ = "";
      type_ = 0;
      text_ = "";
      mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerport()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverport_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, type_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTextBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, mediaBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverport_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromAccountBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getToAccountBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTextBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, mediaBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.NotifyNodeSomeOnePrimaryChatToMe}
     *
     * <pre>
     *NOTIFY_NODE_SOMEONE_PRIMARYCHAT_TO_ME = 800001;//通知其他服务器节点某人私聊某人
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.NotifyNodeSomeOnePrimaryChatToMe)
        utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.class, utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverport_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        toAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgNode.internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor;
      }

      public utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe build() {
        utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe buildPartial() {
        utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe result = new utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverip_ = serverip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverport_ = serverport_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromAccount_ = fromAccount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toAccount_ = toAccount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mediaBytes_ = mediaBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe) {
          return mergeFrom((utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe other) {
        if (other == utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe.getDefaultInstance()) return this;
        if (other.hasServerip()) {
          bitField0_ |= 0x00000001;
          serverip_ = other.serverip_;
          onChanged();
        }
        if (other.hasServerport()) {
          setServerport(other.getServerport());
        }
        if (other.hasFromAccount()) {
          bitField0_ |= 0x00000004;
          fromAccount_ = other.fromAccount_;
          onChanged();
        }
        if (other.hasToAccount()) {
          bitField0_ |= 0x00000008;
          toAccount_ = other.toAccount_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000020;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasMediaBytes()) {
          setMediaBytes(other.getMediaBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerip()) {
          
          return false;
        }
        if (!hasServerport()) {
          
          return false;
        }
        if (!hasFromAccount()) {
          
          return false;
        }
        if (!hasToAccount()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgNode.NotifyNodeSomeOnePrimaryChatToMe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverip_ = "";
      /**
       * <code>required string serverip = 1;</code>
       */
      public boolean hasServerip() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverip = 1;</code>
       */
      public java.lang.String getServerip() {
        java.lang.Object ref = serverip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServeripBytes() {
        java.lang.Object ref = serverip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       */
      public Builder setServerip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       */
      public Builder clearServerip() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverip_ = getDefaultInstance().getServerip();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       */
      public Builder setServeripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }

      private int serverport_ ;
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public boolean hasServerport() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public int getServerport() {
        return serverport_;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public Builder setServerport(int value) {
        bitField0_ |= 0x00000002;
        serverport_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public Builder clearServerport() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverport_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromAccount_ = "";
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public boolean hasFromAccount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public java.lang.String getFromAccount() {
        java.lang.Object ref = fromAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromAccountBytes() {
        java.lang.Object ref = fromAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder clearFromAccount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromAccount_ = getDefaultInstance().getFromAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromAccount = 3;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setFromAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromAccount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toAccount_ = "";
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public boolean hasToAccount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public java.lang.String getToAccount() {
        java.lang.Object ref = toAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToAccountBytes() {
        java.lang.Object ref = toAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setToAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder clearToAccount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toAccount_ = getDefaultInstance().getToAccount();
        onChanged();
        return this;
      }
      /**
       * <code>required string toAccount = 4;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setToAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toAccount_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 5;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 type = 5;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 5;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 5;</code>
       *
       * <pre>
       *聊天类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mediaBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mediaBytes = 7;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public boolean hasMediaBytes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes mediaBytes = 7;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public com.google.protobuf.ByteString getMediaBytes() {
        return mediaBytes_;
      }
      /**
       * <code>optional bytes mediaBytes = 7;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder setMediaBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        mediaBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mediaBytes = 7;</code>
       *
       * <pre>
       *音频文件二进制流
       * </pre>
       */
      public Builder clearMediaBytes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mediaBytes_ = getDefaultInstance().getMediaBytes();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.NotifyNodeSomeOnePrimaryChatToMe)
    }

    static {
      defaultInstance = new NotifyNodeSomeOnePrimaryChatToMe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.NotifyNodeSomeOnePrimaryChatToMe)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ReqNodeServerCreate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ReqNodeServerCreate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgNode.proto\022\010ProtoNet\";\n\023ReqNodeServ" +
      "erCreate\022\020\n\010serverip\030\001 \002(\t\022\022\n\nserverport" +
      "\030\002 \002(\005\"\240\001\n NotifyNodeSomeOnePrimaryChatT" +
      "oMe\022\020\n\010serverip\030\001 \002(\t\022\022\n\nserverport\030\002 \002(" +
      "\005\022\023\n\013fromAccount\030\003 \002(\t\022\021\n\ttoAccount\030\004 \002(" +
      "\t\022\014\n\004type\030\005 \002(\005\022\014\n\004text\030\006 \001(\t\022\022\n\nmediaBy" +
      "tes\030\007 \001(\014B\026\n\024utouu.im.protobuf.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoNet_ReqNodeServerCreate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoNet_ReqNodeServerCreate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ReqNodeServerCreate_descriptor,
        new java.lang.String[] { "Serverip", "Serverport", });
    internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_NotifyNodeSomeOnePrimaryChatToMe_descriptor,
        new java.lang.String[] { "Serverip", "Serverport", "FromAccount", "ToAccount", "Type", "Text", "MediaBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
