// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgServer.proto

package utouu.im.protobuf.pb;

public final class MsgServer {
  private MsgServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResManagerSomeOnePrimaryTextChatToMeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.ResManagerSomeOnePrimaryTextChatToMe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    boolean hasChatText();
    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    java.lang.String getChatText();
    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getChatTextBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.ResManagerSomeOnePrimaryTextChatToMe}
   *
   * <pre>
   *RES_MANAGER_SOMEONEPRIMARYTEXTCHATTOME  = 900001;//返回后台sdk某人给我私聊了文本消息
   * </pre>
   */
  public static final class ResManagerSomeOnePrimaryTextChatToMe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.ResManagerSomeOnePrimaryTextChatToMe)
      ResManagerSomeOnePrimaryTextChatToMeOrBuilder {
    // Use ResManagerSomeOnePrimaryTextChatToMe.newBuilder() to construct.
    private ResManagerSomeOnePrimaryTextChatToMe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResManagerSomeOnePrimaryTextChatToMe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResManagerSomeOnePrimaryTextChatToMe defaultInstance;
    public static ResManagerSomeOnePrimaryTextChatToMe getDefaultInstance() {
      return defaultInstance;
    }

    public ResManagerSomeOnePrimaryTextChatToMe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResManagerSomeOnePrimaryTextChatToMe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              chatText_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgServer.internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgServer.internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.class, utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.Builder.class);
    }

    public static com.google.protobuf.Parser<ResManagerSomeOnePrimaryTextChatToMe> PARSER =
        new com.google.protobuf.AbstractParser<ResManagerSomeOnePrimaryTextChatToMe>() {
      public ResManagerSomeOnePrimaryTextChatToMe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResManagerSomeOnePrimaryTextChatToMe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResManagerSomeOnePrimaryTextChatToMe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CHATTEXT_FIELD_NUMBER = 1;
    private java.lang.Object chatText_;
    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public boolean hasChatText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public java.lang.String getChatText() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chatText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chatText = 1;</code>
     *
     * <pre>
     *发送内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChatTextBytes() {
      java.lang.Object ref = chatText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      chatText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChatText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getChatTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getChatTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.ResManagerSomeOnePrimaryTextChatToMe}
     *
     * <pre>
     *RES_MANAGER_SOMEONEPRIMARYTEXTCHATTOME  = 900001;//返回后台sdk某人给我私聊了文本消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.ResManagerSomeOnePrimaryTextChatToMe)
        utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgServer.internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgServer.internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.class, utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        chatText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgServer.internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor;
      }

      public utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe build() {
        utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe buildPartial() {
        utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe result = new utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chatText_ = chatText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe) {
          return mergeFrom((utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe other) {
        if (other == utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe.getDefaultInstance()) return this;
        if (other.hasChatText()) {
          bitField0_ |= 0x00000001;
          chatText_ = other.chatText_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChatText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgServer.ResManagerSomeOnePrimaryTextChatToMe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object chatText_ = "";
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public boolean hasChatText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public java.lang.String getChatText() {
        java.lang.Object ref = chatText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            chatText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChatTextBytes() {
        java.lang.Object ref = chatText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        chatText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder clearChatText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chatText_ = getDefaultInstance().getChatText();
        onChanged();
        return this;
      }
      /**
       * <code>required string chatText = 1;</code>
       *
       * <pre>
       *发送内容
       * </pre>
       */
      public Builder setChatTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        chatText_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.ResManagerSomeOnePrimaryTextChatToMe)
    }

    static {
      defaultInstance = new ResManagerSomeOnePrimaryTextChatToMe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.ResManagerSomeOnePrimaryTextChatToMe)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MsgServer.proto\022\010ProtoNet\"8\n$ResManage" +
      "rSomeOnePrimaryTextChatToMe\022\020\n\010chatText\030" +
      "\001 \002(\tB\026\n\024utouu.im.protobuf.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_ResManagerSomeOnePrimaryTextChatToMe_descriptor,
        new java.lang.String[] { "ChatText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
