// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgServerBroad.proto

package utouu.im.protobuf.pb;

public final class MsgServerBroad {
  private MsgServerBroad() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotifyServerBroadMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoNet.NotifyServerBroadMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code ProtoNet.NotifyServerBroadMsg}
   *
   * <pre>
   *NOTIFY_SERVER_BROAD_MSG = 300001;//服务器通知消息
   * </pre>
   */
  public static final class NotifyServerBroadMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoNet.NotifyServerBroadMsg)
      NotifyServerBroadMsgOrBuilder {
    // Use NotifyServerBroadMsg.newBuilder() to construct.
    private NotifyServerBroadMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotifyServerBroadMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotifyServerBroadMsg defaultInstance;
    public static NotifyServerBroadMsg getDefaultInstance() {
      return defaultInstance;
    }

    public NotifyServerBroadMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyServerBroadMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utouu.im.protobuf.pb.MsgServerBroad.internal_static_ProtoNet_NotifyServerBroadMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utouu.im.protobuf.pb.MsgServerBroad.internal_static_ProtoNet_NotifyServerBroadMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.class, utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<NotifyServerBroadMsg> PARSER =
        new com.google.protobuf.AbstractParser<NotifyServerBroadMsg>() {
      public NotifyServerBroadMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyServerBroadMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyServerBroadMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     *
     * <pre>
     *文字聊天内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNet.NotifyServerBroadMsg}
     *
     * <pre>
     *NOTIFY_SERVER_BROAD_MSG = 300001;//服务器通知消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoNet.NotifyServerBroadMsg)
        utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return utouu.im.protobuf.pb.MsgServerBroad.internal_static_ProtoNet_NotifyServerBroadMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return utouu.im.protobuf.pb.MsgServerBroad.internal_static_ProtoNet_NotifyServerBroadMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.class, utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.Builder.class);
      }

      // Construct using utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utouu.im.protobuf.pb.MsgServerBroad.internal_static_ProtoNet_NotifyServerBroadMsg_descriptor;
      }

      public utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg getDefaultInstanceForType() {
        return utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.getDefaultInstance();
      }

      public utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg build() {
        utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg buildPartial() {
        utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg result = new utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg) {
          return mergeFrom((utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg other) {
        if (other == utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (utouu.im.protobuf.pb.MsgServerBroad.NotifyServerBroadMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       *
       * <pre>
       *文字聊天内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNet.NotifyServerBroadMsg)
    }

    static {
      defaultInstance = new NotifyServerBroadMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNet.NotifyServerBroadMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNet_NotifyServerBroadMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNet_NotifyServerBroadMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024MsgServerBroad.proto\022\010ProtoNet\"$\n\024Noti" +
      "fyServerBroadMsg\022\014\n\004text\030\001 \001(\tB\026\n\024utouu." +
      "im.protobuf.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoNet_NotifyServerBroadMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoNet_NotifyServerBroadMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoNet_NotifyServerBroadMsg_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
